spring:
  application:
    name: task-management-server
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.0.10.156:3306/tms?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=CTT
    username: root
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://10.0.10.156:1111/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 50001

logging:
  path: ./logs

task:
  limit: 20
